<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>060b6028-370b-44e6-b61f-1c474447b31e</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fms.Interface\Fms.Interface.csproj" />
    <ProjectReference Include="..\Fms.Model\Fms.Model.csproj" />
    <ProjectReference Include="..\Fms.Repository\Fms.Repository.csproj" />
    <ProjectReference Include="..\Fms.Service\Fms.Service.csproj" />
  </ItemGroup>

</Project>
