namespace Fms.Model.Entities;

/// <summary>A form definition (a.k.a. dataset), belonging to a space. Id and SpaceId are
/// uuid strings (backend-standard §6.1.1), generated by the DB (gen_random_uuid).</summary>
public class Form : IAuditable
{
    public string Id { get; set; } = null!;

    public string SpaceId { get; set; } = null!;

    public Space Space { get; set; } = null!;

    public string Name { get; set; } = null!;

    /// <summary>Standard JSON Schema (draft 2020-12), stored as <c>jsonb</c>.</summary>
    public string Schema { get; set; } = null!;

    public string? CreatedBy { get; set; }
    public DateTimeOffset CreatedOn { get; set; }
    public string? LastModifiedBy { get; set; }
    public DateTimeOffset LastModifiedOn { get; set; }

    public List<Submission> Submissions { get; } = [];
}
