namespace Fms.Model.Entities;

/// <summary>Top-level grouping of forms; the coarsest permission target. Id is a
/// uuid string (backend-standard §6.1.1), generated by the DB (gen_random_uuid).</summary>
public class Space : IAuditable
{
    public string Id { get; set; } = null!;

    public string Name { get; set; } = null!;

    public string? CreatedBy { get; set; }
    public DateTimeOffset CreatedOn { get; set; }
    public string? LastModifiedBy { get; set; }
    public DateTimeOffset LastModifiedOn { get; set; }

    public List<Form> Forms { get; } = [];
}
