namespace Fms.Model.Entities;

/// <summary>One user's filled-in data for a form, stored as <c>jsonb</c>. Id, FormId and
/// UserId are uuid strings (backend-standard §6.1.1), generated by the DB (gen_random_uuid).</summary>
public class Submission : IAuditable
{
    public string Id { get; set; } = null!;

    public string FormId { get; set; } = null!;

    public Form Form { get; set; } = null!;

    public string UserId { get; set; } = null!;

    public User User { get; set; } = null!;

    /// <summary>The submitted values as JSON, stored as <c>jsonb</c>.</summary>
    public string Data { get; set; } = null!;

    public string? CreatedBy { get; set; }
    public DateTimeOffset CreatedOn { get; set; }
    public string? LastModifiedBy { get; set; }
    public DateTimeOffset LastModifiedOn { get; set; }
}
