namespace Fms.Model.Entities;

/// <summary>A platform user, authenticated via Entra ID (feature 03). No credentials stored.
/// Id is a uuid string (backend-standard §6.1.1), generated by the DB (gen_random_uuid).</summary>
public class User : IAuditable
{
    public string Id { get; set; } = null!;

    /// <summary>Entra ID object id (the <c>sub</c>/<c>oid</c> claim). Unique external identity.</summary>
    public string EntraObjectId { get; set; } = null!;

    public string Email { get; set; } = null!;

    public string Name { get; set; } = null!;

    /// <summary>Either <c>admin</c> or <c>user</c> (seeded from <c>ADMIN_USER_IDS</c>, feature 03).</summary>
    public string Role { get; set; } = "user";

    public string? CreatedBy { get; set; }
    public DateTimeOffset CreatedOn { get; set; }
    public string? LastModifiedBy { get; set; }
    public DateTimeOffset LastModifiedOn { get; set; }

    public List<Submission> Submissions { get; } = [];
}
