<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Fms.Interface\Fms.Interface.csproj" />
    <ProjectReference Include="..\Fms.Model\Fms.Model.csproj" />
  </ItemGroup>

</Project>
